DROP DATABASE IF EXISTS `animadio`;
CREATE DATABASE `animadio` CHARACTER SET utf8;

USE `animadio`;

CREATE TABLE `Breakpoint` (
    `id`        TINYINT     UNSIGNED    PRIMARY KEY AUTO_INCREMENT,
    `media`     CHAR(2)     NOT NULL    UNIQUE,
    `width`     VARCHAR(10) NOT NULL    UNIQUE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `AnimationCat` (
    `id`        TINYINT     UNSIGNED    PRIMARY KEY AUTO_INCREMENT,
    `category`  VARCHAR(10) NOT NULL    UNIQUE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `VariableCat` (
    `id`        TINYINT     UNSIGNED    PRIMARY KEY AUTO_INCREMENT,
    `category`  VARCHAR(10) NOT NULL    UNIQUE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `ClassCat` (
    `id`        TINYINT     UNSIGNED    PRIMARY KEY AUTO_INCREMENT,
    `category`  VARCHAR(10) NOT NULL    UNIQUE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `ClassState` (
    `id`        TINYINT     UNSIGNED    PRIMARY KEY AUTO_INCREMENT,
    `state`     VARCHAR(10) NOT NULL    UNIQUE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `Animation` (
    `id`            TINYINT     UNSIGNED    PRIMARY KEY AUTO_INCREMENT,
    `category_id`   TINYINT     UNSIGNED    NOT NULL,
    `name`          VARCHAR(10) NOT NULL    UNIQUE,
    `effect`        VARCHAR(40) NOT NULL    UNIQUE,
    CONSTRAINT `animation_category` FOREIGN KEY (`category_id`) REFERENCES `AnimationCat`(`id`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `Variable` (
    `id`            SMALLINT    UNSIGNED    PRIMARY KEY AUTO_INCREMENT,
    `category_id`   TINYINT     UNSIGNED    NOT NULL,
    `name`          VARCHAR(40) NOT NULL    UNIQUE,
    CONSTRAINT `variable_category` FOREIGN KEY (`category_id`) REFERENCES `VariableCat`(`id`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `Class` (
    `id`            SMALLINT    UNSIGNED    PRIMARY KEY AUTO_INCREMENT,
    `category_id`   TINYINT     UNSIGNED    NOT NULL,
    `media`         TINYINT     UNSIGNED    NOT NULL,
    `concat`        TINYINT     UNSIGNED    NOT NULL,
    `state_id`      TINYINT     UNSIGNED    NOT NULL,
    `name`          VARCHAR(20) NOT NULL    UNIQUE,
    CONSTRAINT `class_category` FOREIGN KEY (`category_id`) REFERENCES `ClassCat`(`id`),
    CONSTRAINT `class_state`    FOREIGN KEY (`state_id`)    REFERENCES `ClassState`(`id`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `Theme` (
    `id`            TINYINT     UNSIGNED    PRIMARY KEY AUTO_INCREMENT,
    `name`          VARCHAR(10) NOT NULL    UNIQUE,
    `link`          VARCHAR(10) NOT NULL    UNIQUE,
    `definition`    VARCHAR(50) NOT NULL    UNIQUE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO `Breakpoint`
(`media`, `width`) VALUES
('tn',  '0'),
('sm',  '576px'),
('md',  '768px'),
('lg',  '992px'),
('xl',  '1200px'),
('wd',  '1600px');

INSERT INTO `AnimationCat`
(`category`) VALUES
('translate'),
('rotate'),
('scale'),
('skew');

INSERT INTO `VariableCat`
(`category`) VALUES
('font'),
('color'),
('transform'),
('tags'),
('flex/grid'),
('container'),
('margin'),
('border'),
('padding'),
('height'),
('width'),
('shadow'),
('anima');

INSERT INTO `ClassCat`
(`category`) VALUES
('display'),
('flex'),
('grid'),
('gap'),
('place'),
('position'),
('container'),
('margin'),
('border'),
('padding'),
('height'),
('width'),
('font'),
('text'),
('color'),
('shadow'),
('anima'),
('cursor');

INSERT INTO `ClassState`
(`state`) VALUES
('no'),
('global'),
('helpers');

INSERT INTO `Animation`
(`category_id`, `name`, `effect`) VALUES
(1, 'slideT',   'slide to the top'),
(1, 'slideR',   'slide to the right'),
(1, 'slideB',   'slide to the bottom'),
(1, 'slideL',   'slide to the left'),
(2, 'turn',     'simple rotation'),
(2, 'turnX',    'x-axis rotation'),
(2, 'turnY',    'y-axis rotation'),
(2, 'turnXY',   'rotation on the x & y axes'),
(2, 'turnXZ',   'rotation on the x & z axes'),
(2, 'turnYZ',   'rotation on the y & z axes'),
(2, 'turn3D',   'rotation on 3 axes'),
(3, 'bounce',   'rebound'),
(3, 'grow',     'magnification'),
(3, 'shrink',   'narrowing'),
(3, 'flipX',    'flipping on the x-axis'),
(3, 'flipY',    'flipping on the y-axis'),
(3, 'openX',    'x-axis magnification'),
(3, 'openY',    'y-axis magnification'),
(3, 'flipperX', 'flipping & magnification on the x-axis'),
(3, 'flipperY', 'flipping & magnification on the y-axis'),
(4, 'twistT',   'half distorsion to the top'),
(4, 'twistR',   'half distorsion to the right'),
(4, 'twistB',   'half distorsion to the bottom'),
(4, 'twistL',   'half distorsion to the left');

INSERT INTO `Variable`
(`category_id`, `name`) VALUES
(1,     'serif'),
(1,     'sans-serif'),
(1,     'monospace'),
(1,     'cursive'),
(1,     'fantasy'),
(2,     'primary'),
(2,     'secondary'),
(2,     'pink'),
(2,     'red'),
(2,     'orange'),
(2,     'yellow'),
(2,     'brown'),
(2,     'green'),
(2,     'cyan'),
(2,     'blue'),
(2,     'violet'),
(2,     'black'),
(2,     'gray'),
(2,     'grey'),
(2,     'white'),
(2,     'fb'),
(2,     'gh'),
(2,     'in'),
(2,     'pp'),
(2,     'tw'),
(2,     'opacity-dark'),
(2,     'opacity-light'),
(2,     'primary-dark'),
(2,     'secondary-dark'),
(2,     'pink-dark'),
(2,     'red-dark'),
(2,     'orange-dark'),
(2,     'yellow-dark'),
(2,     'brown-dark'),
(2,     'green-dark'),
(2,     'cyan-dark'),
(2,     'blue-dark'),
(2,     'violet-dark'),
(2,     'black-dark'),
(2,     'gray-dark'),
(2,     'grey-dark'),
(2,     'white-dark'),
(2,     'primary-light'),
(2,     'secondary-light'),
(2,     'pink-light'),
(2,     'red-light'),
(2,     'orange-light'),
(2,     'yellow-light'),
(2,     'brown-light'),
(2,     'green-light'),
(2,     'cyan-light'),
(2,     'blue-light'),
(2,     'violet-light'),
(2,     'black-light'),
(2,     'gray-light'),
(2,     'grey-light'),
(2,     'white-light'),
(3,     'slideT'),
(3,     'slideR'),
(3,     'slideB'),
(3,     'slideL'),
(3,     'turn'),
(3,     'turnX'),
(3,     'turnY'),
(3,     'turnXY'),
(3,     'turnXZ'),
(3,     'turnYZ'),
(3,     'turn3D'),
(3,     'bounce'),
(3,     'grow'),
(3,     'shrink'),
(3,     'flipX'),
(3,     'flipY'),
(3,     'openX'),
(3,     'openY'),
(3,     'flipperX'),
(3,     'flipperY'),
(3,     'twistT'),
(3,     'twistR'),
(3,     'twistB'),
(3,     'twistL'),
(4,     'all-box-sizing'),
(4,     'target-margins'),
(4,     'html-font-size'),
(4,     'html-scroll-behavior'),
(4,     'body-background-color'),
(4,     'body-color'),
(4,     'body-font-size'),
(4,     'body-line-height'),
(4,     'body-scroll-behavior'),
(4,     'main-text-align'),
(4,     'article-margin-bottom'),
(4,     'title-font-family'),
(4,     'title-font-size'),
(4,     'title-text-align'),
(4,     'title-text-transform'),
(4,     'title-color'),
(4,     'link-outline'),
(4,     'link-text-decoration'),
(4,     'link-color'),
(4,     'list-margin'),
(4,     'list-padding'),
(4,     'list-style'),
(4,     'figure-margin'),
(4,     'img-height'),
(4,     'img-max-width'),
(4,     'img-object-fit'),
(4,     'table-border-collapse'),
(4,     'table-margin'),
(4,     'table-text-align'),
(4,     'table-vertical-align'),
(4,     'code-overflow'),
(4,     'code-margin'),
(4,     'code-padding'),
(4,     'code-width'),
(4,     'code-text-align'),
(4,     'code-background-color'),
(4,     'code-color'),
(5,     'flex-place-content'),
(5,     'column-padding'),
(5,     'row-padding'),
(5,     'grid-max-width'),
(5,     'grid-margin'),
(5,     'gap-tn'),
(5,     'gap-sm'),
(5,     'gap-md'),
(5,     'gap-lg'),
(5,     'gap-wd'),
(6,     'container-max-width'),
(7,     'margin-none'),
(7,     'margin-sm'),
(7,     'margin-md'),
(7,     'margin-lg'),
(7,     'margin-top-sm'),
(7,     'margin-top-md'),
(7,     'margin-top-lg'),
(7,     'margin-right-sm'),
(7,     'margin-right-md'),
(7,     'margin-right-lg'),
(7,     'margin-bottom-sm'),
(7,     'margin-bottom-md'),
(7,     'margin-bottom-lg'),
(7,     'margin-left-sm'),
(7,     'margin-left-md'),
(7,     'margin-left-lg'),
(8,     'border-width-sm'),
(8,     'border-width-md'),
(8,     'border-width-lg'),
(8,     'border-radius-square'),
(8,     'border-radius-curve'),
(8,     'border-radius-round'),
(8,     'border-radius-circle'),
(9,     'padding-none'),
(9,     'padding-sm'),
(9,     'padding-md'),
(9,     'padding-lg'),
(9,     'padding-top-sm'),
(9,     'padding-top-md'),
(9,     'padding-top-lg'),
(9,     'padding-right-sm'),
(9,     'padding-right-md'),
(9,     'padding-right-lg'),
(9,     'padding-bottom-sm'),
(9,     'padding-bottom-md'),
(9,     'padding-bottom-lg'),
(9,     'padding-left-sm'),
(9,     'padding-left-md'),
(9,     'padding-left-lg'),
(10,    'height-sm'),
(10,    'height-md'),
(10,    'height-lg'),
(10,    'max-height-sm'),
(10,    'max-height-md'),
(10,    'max-height-lg'),
(10,    'min-height-sm'),
(10,    'min-height-md'),
(10,    'min-height-lg'),
(11,    'width-sm'),
(11,    'width-md'),
(11,    'width-lg'),
(11,    'max-width-sm'),
(11,    'max-width-md'),
(11,    'max-width-lg'),
(11,    'min-width-sm'),
(11,    'min-width-md'),
(11,    'min-width-lg'),
(12,    'box-shadow-sm'),
(12,    'box-shadow-md'),
(12,    'box-shadow-lg'),
(12,    'box-shadow-blur'),
(12,    'box-shadow-blur-sm'),
(12,    'box-shadow-blur-md'),
(12,    'box-shadow-blur-lg'),
(12,    'box-shadow-spread'),
(12,    'box-shadow-spread-sm'),
(12,    'box-shadow-spread-md'),
(12,    'box-shadow-spread-lg'),
(13,    'animation-duration'),
(13,    'animation-duration-sm'),
(13,    'animation-duration-md'),
(13,    'animation-duration-lg'),
(13,    'animation-timing-funtion-linear'),
(13,    'animation-timing-funtion-in'),
(13,    'animation-timing-funtion-out'),
(13,    'animation-timing-funtion-inout'),
(13,    'animation-timing-funtion-start'),
(13,    'animation-timing-funtion-end'),
(13,    'animation-iteration-count-few'),
(13,    'animation-iteration-count-many'),
(13,    'animation-iteration-count-loop'),
(13,    'animation-delay-min'),
(13,    'animation-delay-max');

INSERT INTO `Class`
(`category_id`, `media`, `concat`, `state_id`, `name`) VALUES
(1,     1,  0,  2,  'none'),
(1,     1,  0,  2,  'flex'),
(1,     1,  0,  2,  'block'),
(1,     1,  0,  2,  'inline'),
(1,     1,  0,  2,  'inflex'),
(1,     1,  0,  2,  'inblock'),
(2,     0,  0,  1,  'col'),
(2,     0,  0,  1,  'col-rev'),
(2,     0,  0,  1,  'row'),
(2,     0,  0,  1,  'row-rev'),
(3,     0,  1,  1,  'grid'),
(3,     1,  1,  1,  'grid-2tn'),
(3,     1,  1,  1,  'grid-3tn'),
(3,     1,  1,  1,  'grid-4tn'),
(3,     1,  1,  1,  'grid-5tn'),
(3,     1,  1,  1,  'grid-6tn'),
(3,     1,  1,  1,  'grid-7tn'),
(3,     1,  1,  1,  'grid-8tn'),
(3,     1,  1,  1,  'grid-9tn'),
(3,     1,  1,  1,  'grid-10tn'),
(3,     1,  1,  1,  'grid-11tn'),
(3,     1,  1,  1,  'grid-12tn'),
(4,     1,  1,  1,  'gap-1tn'),
(4,     1,  1,  1,  'gap-2tn'),
(4,     1,  1,  1,  'gap-3tn'),
(4,     1,  1,  1,  'gap-4tn'),
(4,     1,  1,  1,  'gap-5tn'),
(4,     1,  1,  1,  'gap-6tn'),
(5,     1,  0,  1,  'content-start'),
(5,     1,  0,  1,  'content-end'),
(5,     1,  0,  1,  'content-around'),
(5,     1,  0,  1,  'content-between'),
(5,     1,  0,  1,  'content-evenly'),
(5,     1,  0,  1,  'content-center'),
(5,     1,  0,  1,  'content-stretch'),
(5,     1,  0,  1,  'items-base'),
(5,     1,  0,  1,  'items-start'),
(5,     1,  0,  1,  'items-end'),
(5,     1,  0,  1,  'items-normal'),
(5,     1,  0,  1,  'items-center'),
(5,     1,  0,  1,  'items-stretch'),
(5,     1,  0,  1,  'self-base'),
(5,     1,  0,  1,  'self-start'),
(5,     1,  0,  1,  'self-end'),
(5,     1,  0,  1,  'self-auto'),
(5,     1,  0,  1,  'self-normal'),
(5,     1,  0,  1,  'self-center'),
(5,     1,  0,  1,  'self-stretch'),
(6,     1,  0,  2,  'absolute'),
(6,     1,  0,  2,  'fixed'),
(6,     1,  0,  2,  'relative'),
(6,     1,  0,  2,  'sticky'),
(7,     0,  1,  1,  'container'),
(7,     1,  1,  1,  'container-50tn'),
(7,     1,  1,  1,  'container-60tn'),
(7,     1,  1,  1,  'container-70tn'),
(7,     1,  1,  1,  'container-80tn'),
(7,     1,  1,  1,  'container-90tn'),
(8,     0,  0,  2,  'mar-none'),
(8,     0,  0,  2,  'mar-sm'),
(8,     0,  0,  2,  'mar-md'),
(8,     0,  0,  2,  'mar-lg'),
(8,     0,  0,  2,  'mar-top-sm'),
(8,     0,  0,  2,  'mar-top-md'),
(8,     0,  0,  2,  'mar-top-lg'),
(8,     0,  0,  2,  'mar-right-sm'),
(8,     0,  0,  2,  'mar-right-md'),
(8,     0,  0,  2,  'mar-right-lg'),
(8,     0,  0,  2,  'mar-bot-sm'),
(8,     0,  0,  2,  'mar-bot-md'),
(8,     0,  0,  2,  'mar-bot-lg'),
(8,     0,  0,  2,  'mar-left-sm'),
(8,     0,  0,  2,  'mar-left-md'),
(8,     0,  0,  2,  'mar-left-lg'),
(9,     0,  0,  3,  'bord-dash'),
(9,     0,  0,  3,  'bord-dot'),
(9,     0,  0,  3,  'bord-solid'),
(9,     0,  0,  3,  'bord-double'),
(9,     0,  0,  3,  'bord-groove'),
(9,     0,  0,  3,  'bord-ridge'),
(9,     0,  0,  3,  'bord-in'),
(9,     0,  0,  3,  'bord-out'),
(9,     0,  0,  3,  'bord-tn'),
(9,     0,  0,  3,  'bord-sm'),
(9,     0,  0,  3,  'bord-md'),
(9,     0,  0,  3,  'bord-lg'),
(9,     0,  0,  3,  'bord-xl'),
(9,     0,  0,  3,  'bord-wd'),
(9,     0,  0,  3,  'bord-square'),
(9,     0,  0,  3,  'bord-curve'),
(9,     0,  0,  3,  'bord-round'),
(9,     0,  0,  3,  'bord-circle'),
(9,     0,  0,  3,  'bord-primary'),
(9,     0,  0,  3,  'bord-secondary'),
(9,     0,  0,  3,  'bord-pink'),
(9,     0,  0,  3,  'bord-red'),
(9,     0,  0,  3,  'bord-orange'),
(9,     0,  0,  3,  'bord-yellow'),
(9,     0,  0,  3,  'bord-brown'),
(9,     0,  0,  3,  'bord-green'),
(9,     0,  0,  3,  'bord-cyan'),
(9,     0,  0,  3,  'bord-blue'),
(9,     0,  0,  3,  'bord-violet'),
(9,     0,  0,  3,  'bord-black'),
(9,     0,  0,  3,  'bord-gray'),
(9,     0,  0,  3,  'bord-grey'),
(9,     0,  0,  3,  'bord-white'),
(10,    0,  0,  2,  'pad-none'),
(10,    0,  0,  2,  'pad-sm'),
(10,    0,  0,  2,  'pad-md'),
(10,    0,  0,  2,  'pad-lg'),
(10,    0,  0,  2,  'pad-top-sm'),
(10,    0,  0,  2,  'pad-top-md'),
(10,    0,  0,  2,  'pad-top-lg'),
(10,    0,  0,  2,  'pad-right-sm'),
(10,    0,  0,  2,  'pad-right-md'),
(10,    0,  0,  2,  'pad-right-lg'),
(10,    0,  0,  2,  'pad-bot-sm'),
(10,    0,  0,  2,  'pad-bot-md'),
(10,    0,  0,  2,  'pad-bot-lg'),
(10,    0,  0,  2,  'pad-left-sm'),
(10,    0,  0,  2,  'pad-left-md'),
(10,    0,  0,  2,  'pad-left-lg'),
(11,    0,  0,  2,  'height-sm'),
(11,    0,  0,  2,  'height-md'),
(11,    0,  0,  2,  'height-lg'),
(11,    0,  0,  2,  'max-h-sm'),
(11,    0,  0,  2,  'max-h-md'),
(11,    0,  0,  2,  'max-h-lg'),
(11,    0,  0,  2,  'min-h-sm'),
(11,    0,  0,  2,  'min-h-md'),
(11,    0,  0,  2,  'min-h-lg'),
(12,    0,  0,  2,  'width-sm'),
(12,    0,  0,  2,  'width-md'),
(12,    0,  0,  2,  'width-lg'),
(12,    0,  0,  2,  'max-w-sm'),
(12,    0,  0,  2,  'max-w-md'),
(12,    0,  0,  2,  'max-w-lg'),
(12,    0,  0,  2,  'min-w-sm'),
(12,    0,  0,  2,  'min-w-md'),
(12,    0,  0,  2,  'min-w-lg'),
(13,    0,  0,  3,  'font-bold'),
(13,    0,  0,  3,  'font-italic'),
(13,    0,  0,  3,  'font-oblique'),
(13,    0,  0,  3,  'font-sans-serif'),
(13,    0,  0,  3,  'font-serif'),
(13,    0,  0,  3,  'font-monospace'),
(13,    0,  0,  3,  'font-cursive'),
(13,    0,  0,  3,  'font-fantasy'),
(14,    0,  0,  3,  'align-center'),
(14,    0,  0,  3,  'align-justify'),
(14,    0,  0,  3,  'align-right'),
(14,    0,  0,  3,  'align-left'),
(14,    0,  0,  3,  'trans-cap'),
(14,    0,  0,  3,  'trans-up'),
(14,    0,  0,  3,  'trans-low'),
(14,    0,  0,  3,  'deco-none'),
(14,    0,  0,  3,  'deco-under'),
(14,    0,  0,  3,  'deco-over'),
(14,    0,  0,  3,  'deco-through'),
(14,    0,  0,  3,  'deco-dash'),
(14,    0,  0,  3,  'deco-dot'),
(14,    0,  0,  3,  'deco-double'),
(14,    0,  0,  3,  'deco-solid'),
(14,    0,  0,  3,  'deco-wavy'),
(14,    0,  0,  3,  'deco-primary'),
(14,    0,  0,  3,  'deco-secondary'),
(14,    0,  0,  3,  'deco-pink'),
(14,    0,  0,  3,  'deco-red'),
(14,    0,  0,  3,  'deco-orange'),
(14,    0,  0,  3,  'deco-yellow'),
(14,    0,  0,  3,  'deco-brown'),
(14,    0,  0,  3,  'deco-green'),
(14,    0,  0,  3,  'deco-cyan'),
(14,    0,  0,  3,  'deco-blue'),
(14,    0,  0,  3,  'deco-violet'),
(15,    0,  0,  3,  'primary'),
(15,    0,  0,  3,  'secondary'),
(15,    0,  0,  3,  'pink'),
(15,    0,  0,  3,  'red'),
(15,    0,  0,  3,  'orange'),
(15,    0,  0,  3,  'yellow'),
(15,    0,  0,  3,  'brown'),
(15,    0,  0,  3,  'green'),
(15,    0,  0,  3,  'cyan'),
(15,    0,  0,  3,  'blue'),
(15,    0,  0,  3,  'violet'),
(15,    0,  0,  3,  'black'),
(15,    0,  0,  3,  'gray'),
(15,    0,  0,  3,  'grey'),
(15,    0,  0,  3,  'white'),
(15,    0,  0,  3,  'fb'),
(15,    0,  0,  3,  'gh'),
(15,    0,  0,  3,  'in'),
(15,    0,  0,  3,  'pp'),
(15,    0,  0,  3,  'tw'),
(15,    0,  0,  3,  'bg-primary'),
(15,    0,  0,  3,  'bg-secondary'),
(15,    0,  0,  3,  'bg-pink'),
(15,    0,  0,  3,  'bg-red'),
(15,    0,  0,  3,  'bg-orange'),
(15,    0,  0,  3,  'bg-yellow'),
(15,    0,  0,  3,  'bg-brown'),
(15,    0,  0,  3,  'bg-green'),
(15,    0,  0,  3,  'bg-cyan'),
(15,    0,  0,  3,  'bg-blue'),
(15,    0,  0,  3,  'bg-violet'),
(15,    0,  0,  3,  'bg-black'),
(15,    0,  0,  3,  'bg-gray'),
(15,    0,  0,  3,  'bg-grey'),
(15,    0,  0,  3,  'bg-white'),
(15,    0,  0,  3,  'bg-primary-dark'),
(15,    0,  0,  3,  'bg-secondary-dark'),
(15,    0,  0,  3,  'bg-pink-dark'),
(15,    0,  0,  3,  'bg-red-dark'),
(15,    0,  0,  3,  'bg-orange-dark'),
(15,    0,  0,  3,  'bg-yellow-dark'),
(15,    0,  0,  3,  'bg-brown-dark'),
(15,    0,  0,  3,  'bg-green-dark'),
(15,    0,  0,  3,  'bg-cyan-dark'),
(15,    0,  0,  3,  'bg-blue-dark'),
(15,    0,  0,  3,  'bg-violet-dark'),
(15,    0,  0,  3,  'bg-black-dark'),
(15,    0,  0,  3,  'bg-gray-dark'),
(15,    0,  0,  3,  'bg-grey-dark'),
(15,    0,  0,  3,  'bg-white-dark'),
(15,    0,  0,  3,  'bg-pink-primary'),
(15,    0,  0,  3,  'bg-pink-secondary'),
(15,    0,  0,  3,  'bg-pink-light'),
(15,    0,  0,  3,  'bg-red-light'),
(15,    0,  0,  3,  'bg-orange-light'),
(15,    0,  0,  3,  'bg-yellow-light'),
(15,    0,  0,  3,  'bg-brown-light'),
(15,    0,  0,  3,  'bg-green-light'),
(15,    0,  0,  3,  'bg-cyan-light'),
(15,    0,  0,  3,  'bg-blue-light'),
(15,    0,  0,  3,  'bg-violet-light'),
(15,    0,  0,  3,  'bg-black-light'),
(15,    0,  0,  3,  'bg-gray-light'),
(15,    0,  0,  3,  'bg-grey-light'),
(15,    0,  0,  3,  'bg-white-light'),
(16,    0,  0,  3,  'shabox-sm'),
(16,    0,  0,  3,  'shabox-in-sm'),
(16,    0,  0,  3,  'shabox-md'),
(16,    0,  0,  3,  'shabox-in-md'),
(16,    0,  0,  3,  'shabox-lg'),
(16,    0,  0,  3,  'shabox-in-lg'),
(16,    0,  0,  3,  'shabox-blur'),
(16,    0,  0,  3,  'shabox-in-blur'),
(16,    0,  0,  3,  'shabox-blur-sm'),
(16,    0,  0,  3,  'shabox-in-blur-sm'),
(16,    0,  0,  3,  'shabox-blur-md'),
(16,    0,  0,  3,  'shabox-in-blur-md'),
(16,    0,  0,  3,  'shabox-blur-lg'),
(16,    0,  0,  3,  'shabox-in-blur-lg'),
(16,    0,  0,  3,  'shabox-spread'),
(16,    0,  0,  3,  'shabox-in-spread'),
(16,    0,  0,  3,  'shabox-spread-sm'),
(16,    0,  0,  3,  'shabox-in-spread-sm'),
(16,    0,  0,  3,  'shabox-spread-md'),
(16,    0,  0,  3,  'shabox-in-spread-md'),
(16,    0,  0,  3,  'shabox-spread-lg'),
(16,    0,  0,  3,  'shabox-in-spread-lg'),
(17,    0,  1,  3,  'anima-slideT'),
(17,    0,  1,  3,  'anima-slideR'),
(17,    0,  1,  3,  'anima-slideB'),
(17,    0,  1,  3,  'anima-slideL'),
(17,    0,  1,  3,  'anima-turn'),
(17,    0,  1,  3,  'anima-turnX'),
(17,    0,  1,  3,  'anima-turnY'),
(17,    0,  1,  3,  'anima-turnXY'),
(17,    0,  1,  3,  'anima-turnXZ'),
(17,    0,  1,  3,  'anima-turnYZ'),
(17,    0,  1,  3,  'anima-turn3D'),
(17,    0,  1,  3,  'anima-bounce'),
(17,    0,  1,  3,  'anima-grow'),
(17,    0,  1,  3,  'anima-shrink'),
(17,    0,  1,  3,  'anima-openX'),
(17,    0,  1,  3,  'anima-openY'),
(17,    0,  1,  3,  'anima-flipX'),
(17,    0,  1,  3,  'anima-flipY'),
(17,    0,  1,  3,  'anima-flipperX'),
(17,    0,  1,  3,  'anima-flipperY'),
(17,    0,  1,  3,  'anima-fallX'),
(17,    0,  1,  3,  'anima-fallY'),
(17,    0,  1,  3,  'anima-twistT'),
(17,    0,  1,  3,  'anima-twistR'),
(17,    0,  1,  3,  'anima-twistB'),
(17,    0,  1,  3,  'anima-twistL'),
(17,    0,  1,  3,  'anima-sm'),
(17,    0,  1,  3,  'anima-md'),
(17,    0,  1,  3,  'anima-lg'),
(17,    0,  1,  3,  'anima-linear'),
(17,    0,  1,  3,  'anima-in'),
(17,    0,  1,  3,  'anima-out'),
(17,    0,  1,  3,  'anima-inout'),
(17,    0,  1,  3,  'anima-start'),
(17,    0,  1,  3,  'anima-end'),
(17,    0,  1,  3,  'anima-few'),
(17,    0,  1,  3,  'anima-many'),
(17,    0,  1,  3,  'anima-loop'),
(17,    0,  1,  3,  'anima-min'),
(17,    0,  1,  3,  'anima-max'),
(17,    0,  1,  3,  'anima-alt'),
(17,    0,  1,  3,  'anima-rev'),
(17,    0,  1,  3,  'anima-altrev'),
(18,    0,  0,  2,  'cursor-cell'),
(18,    0,  0,  2,  'cursor-cross'),
(18,    0,  0,  2,  'cursor-hand'),
(18,    0,  0,  2,  'cursor-help'),
(18,    0,  0,  2,  'cursor-move'),
(18,    0,  0,  2,  'cursor-none'),
(18,    0,  0,  2,  'cursor-text');

INSERT INTO `Theme`
(`name`, `link`, `definition`) VALUES
('Age',     'gOomVEB',   'A theme about our time'),
('Anima',   'zYpZgRq',   'The Animadio theme'),
('Astro',   'rNpyXRL',   'A dark theme like space'),
('Magic',   'yLpMmwN',   'A theme with magic effect'),
('Numeric', 'oNpZKVo',   'A monochrome theme'),
('Spirit',  'wvpJVOO',   'A visual theme for the mind'),
('Tool',    'zYpZgbo',   'A theme about mecanic');
